-- changelog: the pure half of the What's New feature. Handed CHANGELOG.md as
-- plain text, it answers three questions — what releases exist, which ones has
-- this user not seen, and what does one of them look like flattened into the
-- one-paragraph shape the ReaPack script header can hold.
--
-- CHANGELOG.md is the single source of truth (decided 2026-08-08,
-- `.brief/_done/changelog/`): the script's @changelog block and the GitHub
-- release notes are GENERATED from it, and the tool reads it straight for the
-- What's New card and the Settings history. Nothing writes release notes twice.
--
-- Zero reaper.* calls — the file read lives in the entry script, which hands the
-- text in. Unit-tested in tests/changelog_spec.lua.
--
-- The grammar, fixed because this parses it:
--
--   ## 0.3.0 — 2026-08-08          a release; version first, ISO date anywhere
--   ### New                        a group heading
--   - **Waveform** — what changed. an entry: bold area, separator, sentence
--     One extra fact worth it.     optional detail line, indented, no bullet
--
-- Tolerant by design: a line that doesn't match any of those is skipped rather
-- than raising. This file is generated by our own release skill, so a stray line
-- means a hand edit went slightly wrong — losing that one line is a far better
-- failure than a tool that won't open. Nothing is ever INVENTED, though: an
-- entry with no bold prefix simply has no area.

local update_check = require("core.update_check")

local changelog = {}

-- The separators an entry's area word can be followed by, longest first. Written
-- as byte strings rather than pasted characters so it is obvious each is ONE
-- character and not a range in a character class — an em dash cannot go in one.
--
-- The list covers more than the em dash we write, because CHANGELOG.md is a
-- file a human edits on Windows: an editor saving as the system codepage turns
-- the em dash into the single byte 0x97 (0x96 for an en dash), and an unstripped
-- separator ships as a doubled dash in the generated ReaPack header. Caught
-- exactly that way while testing the generator.
local SEPARATORS = {
  "\226\128\148", -- em dash, UTF-8
  "\226\128\147", -- en dash, UTF-8
  "\151",         -- em dash, Windows-1252
  "\150",         -- en dash, Windows-1252
}

-- The group names, in the order they are always shown — never the order they
-- happened to appear in the file. A group outside this list is kept but sorts
-- last, so a typo in a heading is visible rather than silently dropped.
changelog.GROUP_ORDER = { "New", "Improved", "Fixed" }

local function group_rank(name)
  for i, n in ipairs(changelog.GROUP_ORDER) do
    if n:lower() == tostring(name):lower() then return i end
  end
  return #changelog.GROUP_ORDER + 1
end

-- Strip ONE leading separator — spaces, then a dash of any of the forms above
-- (or a plain hyphen), then spaces. One only: a sentence that genuinely starts
-- with a dash keeps it after the separator has been taken.
local function strip_lead(s)
  for _, dash in ipairs(SEPARATORS) do
    local cut, n = s:gsub("^%s*" .. dash .. "%s*", "", 1)
    if n > 0 then return (cut:gsub("^%s+", "")) end
  end
  return (s:gsub("^%s*%-+%s*", ""):gsub("^%s+", ""))
end

-- One entry body ("**Waveform** — start and end points frame what plays.")
-- into its area and its sentence. No bold prefix = no area, text unchanged.
local function split_area(body)
  local area, rest = body:match("^%*%*(.-)%*%*(.*)$")
  if not area then return nil, (body:gsub("^%s+", "")) end
  return area, strip_lead(rest)
end

-- Parse the whole file. Returns releases in the order they appear, each:
--   { version = "0.3.0", date = "2026-08-08", groups = {
--       { name = "New", entries = { { area = ?, text = "…", detail = ? } } } } }
--
-- Releases are NOT re-sorted: the file is written newest-first and that order is
-- what every surface shows. `changelog.since` sorts by version where it matters.
function changelog.parse(text)
  local releases = {}
  if type(text) ~= "string" then return releases end

  local release, group, entry

  for line in (text .. "\n"):gmatch("(.-)\r?\n") do
    local head = line:match("^##%s+([^%s]+)")
    local sub = line:match("^###%s+(.+)$")
    local bullet = line:match("^%s*[%-%*]%s+(.+)$")
    -- A detail line: indented, no bullet, and only meaningful under an entry.
    local detail = line:match("^%s%s+(%S.*)$")

    if head then
      release = { version = head, date = line:match("(%d%d%d%d%-%d%d%-%d%d)"), groups = {} }
      releases[#releases + 1] = release
      group, entry = nil, nil
    elseif sub and release then
      group = { name = (sub:gsub("%s+$", "")), entries = {} }
      release.groups[#release.groups + 1] = group
      entry = nil
    elseif bullet and group then
      local area, text_ = split_area(bullet)
      entry = { area = area, text = text_ }
      group.entries[#group.entries + 1] = entry
    elseif detail and entry then
      -- A second detail line joins the first rather than replacing it: the
      -- release skill wraps long detail across lines, and dropping all but the
      -- last would silently lose half a sentence.
      entry.detail = entry.detail and (entry.detail .. " " .. detail) or detail
    end
  end

  -- Groups into their canonical order, in place. A stable insertion sort: the
  -- lists are three long, and table.sort gives no stability guarantee for the
  -- unknown-heading case that all ranks last.
  for _, r in ipairs(releases) do
    for i = 2, #r.groups do
      local g, j = r.groups[i], i - 1
      local rank = group_rank(g.name)
      while j >= 1 and group_rank(r.groups[j].name) > rank do
        r.groups[j + 1] = r.groups[j]
        j = j - 1
      end
      r.groups[j + 1] = g
    end
  end

  return releases
end

-- The releases strictly newer than `seen`, newest first. A nil/empty `seen` is a
-- first-ever run: it returns NOTHING, deliberately — a new user has no history
-- to catch up on, and greeting them with the notes for versions they never had
-- would read as a fault.
function changelog.since(releases, seen)
  local out = {}
  if type(seen) ~= "string" or seen == "" then return out end
  for _, r in ipairs(releases or {}) do
    if r.version and update_check.compare(r.version, seen) > 0 then
      out[#out + 1] = r
    end
  end
  table.sort(out, function(a, b) return update_check.compare(a.version, b.version) > 0 end)
  return out
end

-- What to write as the seen-mark once `shown` has been read, given the version
-- now running: the NEWEST of the two.
--
-- Marking the running version alone looks obvious and loops forever the moment
-- CHANGELOG.md carries an entry above it — the card shows it, the mark doesn't
-- move past it, and it shows again on every open. Normally that can't happen
-- (the file and the code ship together), but the file is hand-editable, and a
-- popup that cannot be dismissed is a bad answer to a typo. Taking the newest
-- guarantees the mark clears everything just shown, so the card always ends.
function changelog.mark_for(shown, running)
  local mark = running
  for _, r in ipairs(shown or {}) do
    if r.version and (not mark or update_check.compare(r.version, mark) > 0) then
      mark = r.version
    end
  end
  return mark
end

-- One release by exact version string, or nil.
function changelog.find(releases, version)
  for _, r in ipairs(releases or {}) do
    if r.version == version then return r end
  end
  return nil
end

-- One release flattened into a single paragraph — what the ReaPack script
-- header can hold. The header is a Lua comment block: indented lines only, no
-- headings, no blank lines, so the group names become inline labels and the
-- detail lines are dropped (they are the part a small ReaPack box has least room
-- for, and the full text is one click away in the tool).
function changelog.flatten(release)
  if not release then return "" end
  local parts = {}
  for _, g in ipairs(release.groups or {}) do
    local bits = {}
    for _, e in ipairs(g.entries) do
      bits[#bits + 1] = e.area and (e.area .. ": " .. e.text) or e.text
    end
    if #bits > 0 then parts[#parts + 1] = g.name .. " \u{00B7} " .. table.concat(bits, " ") end
  end
  return table.concat(parts, "  ")
end

-- Greedy word wrap. Used by the header generator so a flattened release sits
-- inside the comment block's width; pure and here rather than in the script so
-- the wrapping is pinned by a test like everything else.
function changelog.wrap(text, width)
  local lines, line = {}, ""
  for word in tostring(text):gmatch("%S+") do
    if line == "" then
      line = word
    elseif #line + 1 + #word <= width then
      line = line .. " " .. word
    else
      lines[#lines + 1] = line
      line = word
    end
  end
  if line ~= "" then lines[#lines + 1] = line end
  return lines
end

return changelog
